name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - run: docker compose down
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          clean: false
      - run: docker compose up -d
